/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class HelloWorld */

#ifndef _Included_jniexamples_helloworld_HelloWorld
#define _Included_jniexamples_helloworld_HelloWorld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     HelloWorld
 * Method:    helloNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jniexamples_helloworld_HelloWorld_helloNative
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
